package com.learn;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Demo5 {
    public static void main(String[] args) {
        String url = "jdbc:mysql://127.0.0.1:3306/employees_database";
        try {
            // Establish connection
            Connection conn = DriverManager.getConnection(url, "root", "Root");

            // Create the prepared statement
            PreparedStatement statement = conn.prepareStatement("select * from employees_tbl where salary > ?");

            // Set parameters in prepared statement
            statement.setInt(1, 6000);

            // Execute the statement
            ResultSet resultset = statement.executeQuery();

            // Process the result
            while (resultset.next()) {
                String name = resultset.getString("name");
                int salary = resultset.getInt("salary");
                System.out.printf("%s earns %d\n", name, salary);
            }

        } catch (SQLException e) {
            System.out.println("XXXXXXXXXXXXX");
            e.printStackTrace();
        }
    }
}

/*
 * preparedStatement.executeQuery():
 * Executes the SQL query in this PreparedStatement object and returns the
 * ResultSet object generated by the query.
 * 
 * statement.executeQuery(sql):
 * Executes the given SQL statement, which returns a single ResultSet object.
 * Note: This method cannot be called on a PreparedStatement or
 * CallableStatement.
 */